services:
  web:
    build: ./airbnb_backend
    volumes:
      - ./airbnb_backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env # Remove this line if you don’t need an .env file
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=airbnb
volumes:
  postgres_data:
